# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26bbb266dda7f1201a312815262e786ca204552e46c063e0bbebd71f162dd2eb9f8379f77161e06a191baaf4eff4f8b99eda2e8b4f0328cb183a818c19f56a8b

test:
  secret_key_base: 6944bca917fd087a4c6252b214a17a41ea5c96d8ca9d4ec4cd4c49221c83b281819e81ff88695b6b7282323614082d57f0544ebec4d192dd534f37f71d6d78cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
